### ISSUE TITLE
OAI-PMH Delete Handling

### ISSUE THREAD

**Issue by GoogleCodeExporter** [attiah/the-fascinator#63]
```
At this stage, the cause is unknown. But it occurs inside the OAI Library. We 
should be able to trap this except and prevent the harvest from stalling.

=== harvest.out 
==============================================================================
2012-05-02 16:03:28,965 INFO   FascinatorHome       Set Fascinator home to 
'/opt/app/redbox/home'
2012-05-02 16:03:29,975 INFO   HarvestClient        Loaded File System Storage
2012-05-02 16:03:30,044 INFO   MessagingServices    Starting message queue 
services...
2012-05-02 16:03:30,263 INFO   MessagingServices    Creating new AMQ Producer 
for broker: 'tcp://localhost:9101'
2012-05-02 16:03:30,264 INFO   MessagingServices    Opening new AMQ Session for 
broker: 'tcp://localhost:9101'
2012-05-02 16:03:31,135 INFO   HarvestClient        Started at 
2012-05-02T04:03:31Z
2012-05-02 16:03:31,963 INFO   OaiPmhHarvester      Harvesting all records
2012-05-02 16:03:31,964 INFO   HarvestClient        Loaded harvester: OAI-PMH 
Harvester
2012-05-02 16:03:32,118 DEBUG  Handler              openConnection: 
http://xxxxxxxxxxx.xxxx.edu.au/oai/provider?verb=ListRecords&metadataPrefix=rif
Exception in thread "main" java.lang.NullPointerException
    at org.dom4j.io.XMLWriter.writeElement(XMLWriter.java:900)
    at org.dom4j.io.XMLWriter.write(XMLWriter.java:369)
    at se.kb.xml.XMLUtils.writeXmlTo(XMLUtils.java:55)
    at se.kb.xml.XMLUtils.xmlToString(XMLUtils.java:70)
    at se.kb.oai.pmh.Record.getMetadataAsString(Record.java:107)
    at com.googlecode.fascinator.harvester.oaipmh.OaiPmhHarvester.createOaiPmhDigitalObject(OaiPmhHarvester.java:472)
    at com.googlecode.fascinator.harvester.oaipmh.OaiPmhHarvester.getObjectIdList(OaiPmhHarvester.java:412)
    at com.googlecode.fascinator.HarvestClient.start(HarvestClient.java:256)
    at com.googlecode.fascinator.HarvestClient.main(HarvestClient.java:544)
================================================================================
===============
```

Original issue reported on code.google.com by `greg.pen...@gmail.com` on 2 May 2012 at 10:43

**Comment by GoogleCodeExporter** [comment]
```
Caused by 'delete' records in the feed. The crash is complete and should be 
fixed ASAP. Broader question of what to do with 'delete' records can wait.
```

Original comment by `greg.pen...@gmail.com` on 3 May 2012 at 1:27
- Changed title: **OAI-PMH Delete Handling**
- Added labels: **Priority-Critical**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Critical issue fixed in r3194. Lowering priority. Name changed previously to 
reflect the issue.
```

Original comment by `greg.pen...@gmail.com` on 3 May 2012 at 1:30
- Changed state: **Started**
- Added labels: **Priority-Low**
- Removed labels: **Priority-Critical**

**Comment by GoogleCodeExporter** [comment]
```
Migrated to https://github.com/the-fascinator/the-fascinator/issues/6
```

Original comment by `duncan.q...@gmail.com` on 14 Jan 2013 at 5:18
- Changed state: **MovedToGitHub**
